openapi: 3.0.0
info:
  title: llmkit API
  version: 1.0.0
paths:
  /v1/ui/prompt-eval-runs/{prompt_id}/version/{prompt_version_id}:
    post:
      summary: Execute prompt eval runs
      parameters:
        - name: prompt_id
          in: path
          required: true
          schema:
            type: integer
        - name: prompt_version_id
          in: path
          required: true
          schema:
            type: integer
        - name: rounds
          in: query
          required: false
          schema:
            type: integer
            default: 1
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PromptEvalExecutionRunResponse'
components:
  schemas:
    PromptEvalRunResponse:
      type: object
      properties:
        id:
          type: integer
        run_id:
          type: string
        prompt_version_id:
          type: integer
        prompt_eval_id:
          type: integer
        prompt_eval_name:
          type: string
        score:
          type: integer
          nullable: true
        output:
          type: string
        created_at:
          type: string
        updated_at:
          type: string
    PromptEvalExecutionRunResponse:
      type: object
      properties:
        run_id:
          type: string
        runs:
          type: array
          items:
            $ref: '#/components/schemas/PromptEvalRunResponse'
